---
name: foxy-single-sign-on-config
---
SilverStripe\Admin\LeftAndMain:
  extensions:
    - Dynamic\Foxy\SingleSignOn\Extension\FoxySingleSignOnExtension

Dynamic\Foxy\Parser\Controller\FoxyController:
  extensions:
    - Dynamic\Foxy\SingleSignOn\Extension\FoxyControllerMemberExtension

SilverStripe\Security\Member:
  extensions:
    - Dynamic\Foxy\SingleSignOn\Extension\CustomerExtension

SilverStripe\Forms\GridField\GridFieldDetailForm_ItemRequest:
  extensions:
    - Dynamic\Foxy\SingleSignOn\Extension\MemberItemRequestExtension
